list: $/recipe/recipe/models/recipe/columns.yaml
modelClass: recipe\Recipe\Models\Recipe
title: Recipes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'recipe/recipe/recipes/update/:id'
filter: config_filter.yaml