plugin:
    name: 'recipe.recipe::lang.plugin.name'
    description: 'recipe.recipe::lang.plugin.description'
    author: 'Natwar Singh'
    icon: oc-icon-adjust
    homepage: ''
    category: 'CWS Recipe'
navigation:
    main-recipes:
        label: Recipes
        url: recipe/recipe/recipes
        icon: icon-cutlery
        permissions:
            - manage_recipe
        sideMenu:
            recipes:
                label: 'recipe.recipe::lang.recipe.recipes'
                url: recipe/recipe/recipes
                icon: icon-cutlery
                permissions:
                    - manage_recipe
            categories:
                label: 'recipe.recipe::lang.category.categories'
                url: recipe/recipe/categories
                icon: icon-sitemap
                permissions:
                    - categories_view
    ads:
        label: 'Ads'
        url: recipe/recipe/advertisements
        icon: icon-briefcase
        sideMenu:
            advertisement:
                label: 'recipe.recipe::lang.advertisement'
                url: recipe/recipe/advertisements
                icon: icon-simplybuilt
                permissions:
                    - manage_ads
            adspace:
                label: 'recipe.recipe::lang.advertisements.adspace'
                url: recipe/recipe/adspaces
                icon: icon-sitemap
                permissions:
                    - manage_ads
            report:
                label: Report
                url: recipe/recipe/advertisements/report
                icon: icon-dashboard
                permissions:
                    - manage_ads
permissions:
    manage_recipe:
        tab: 'recipe.recipe::lang.plugin.name'
        label: 'Manage Recipe'
    categories_view:
        tab: 'recipe.recipe::lang.category.categories'
        label: 'recipe.recipe::lang.permission.categories_view'
    manage_ads:
        tab: 'recipe.recipe::lang.advertisement'
        label: 'recipe.recipe::lang.manage_advertisement'
