list: $/recipe/recipe/models/advertisement/columns.yaml
modelClass: recipe\Recipe\Models\Advertisement
title: Advertisements
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'recipe/recipe/advertisements/update/:id'
