adSpaces:
    label: Ad Spaces
    view:
        list: $/recipe/recipe/models/adspace/columns.yaml
        toolbarButtons: add|remove
    manage:
        list: $/recipe/recipe/models/adspace/columns.yaml
        # form: $/recipe/recipe/models/adspace/fields.yaml
        recordsPerPage: 10
        showSearch: true
        # filter: config_filter.yaml
