list: $/recipe/recipe/models/adspace/columns.yaml
modelClass: recipe\Recipe\Models\AdSpace
title: AdSpaces
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'recipe/recipe/adspaces/update/:id'
